logging:
  level:
    org:
      springframework:
        security: TRACE
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: xx
            client-secret: xx
          google:
            client-id: xxx
            client-secret: xxx
          naver:
            client-id: xxx
            client-secret: xxx
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            #naver provider info 찾을 수 있는 데 https://developers.naver.com/docs/login/devguide/devguide.md
